### ISSUE TITLE
Figure out exact PES matching

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo-loihi#11]
The PES learning rule in the emulator and hardware both differ from the Nengo core implementation in some ways. It would be good to get a better understanding of what is different so that we can emulate it better, and choose better constants during the build process.

Specifically, we should:

- [ ] Figure out the exact Nengo core -> hardware learning rate scaling
- [ ] Figure out the exact hardware -> emulator learning rate scaling
- [ ] Vary other parameters (e.g. `pre_synapse`) and ensure that they work on Loihi the same as they work in Nengo core

**Comment by tbekolay** [comment]
Also a note that in order to match the PES rule in all cases, it may be necessary to generate microcode values on the fly. We currently [hardcode them](https://github.com/nengo/nengo-loihi/blob/master/nengo_loihi/loihi_interface.py#L154).

**Comment by drasmuss** [comment]
This was largely resolved in #139, I opened an issue to look at the `pre_synapse` behaviour specifically (#179).
