### ISSUE TITLE
mnist_convnet on chip

### ISSUE THREAD

**Issue by n-getty** [nengo/nengo-loihi#120]
I can run this example with the loihi simulator, though when I try to run on chip it appears the script stalls and then times out:

```
Build finished in 0:00:00                                                                                                                                                            
Optimization finished in 0:00:00                                                                                                                                                     
Construction finished in 0:00:01                                                                                                                                                     
SLURM is being run in background
Connecting to 10.212.98.103:18861
Board type is : nahuku and number of Chips is 8
Running on Nahuku
Args chip=0 cpu=0 .../launcher.bin --chips=1 
Lakemont_driver...
```
I would expect to atleast see the typical
`chip=0 cpu=0 time 100`
logging messages.

Is it possible yet to run this model on chip?

**Comment by drasmuss** [comment]
If it's the `docs/examples/mnist_convnet.ipynb` example from [this PR](https://github.com/nengo/nengo-loihi/pull/81) that you're trying to run, then yes that should work on the chip.  If the Lakemont driver is crashing like that, it often means that there is some incompatibility in the versions between nengo-loihi, nxsdk, and the environment on your host/chip.  A first step would be to try creating a fresh environment following [these instructions](https://www.nengo.ai/nengo-loihi/installation.html) to ensure that all the versions are compatible, and see if that fixes things.

**Comment by drasmuss** [comment]
Going to close this, but let me know if you're still experiencing the issue and we can reopen!
