### ISSUE TITLE
Addition of two inputs is not very accurate for some inputs

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo-loihi#129]
When we have multiple inputs to an Ensemble, we should get addition.  However, for some values this doesn't seem to be very accurate.  For example:

```python
model = nengo.Network(seed=1)
with model:
    stim_a = nengo.Node(0.5)
    stim_b = nengo.Node(0.5)
    
    a = nengo.Ensemble(n_neurons=100, dimensions=1)
    b = nengo.Ensemble(n_neurons=100, dimensions=1)
    
    nengo.Connection(stim_a, a)
    nengo.Connection(stim_b, b)
    
    c = nengo.Ensemble(n_neurons=100, dimensions=1)    
    nengo.Connection(a, c)
    nengo.Connection(b, c)
    
    p_c = nengo.Probe(c, synapse=0.1)
    p_a = nengo.Probe(a, synapse=0.1)    
    p_b = nengo.Probe(b, synapse=0.1)        
```
![image](https://user-images.githubusercontent.com/2380772/47138692-18e75880-d288-11e8-91e8-17009ccb7394.png)

This problem is much reduced by decreasing dt:
```python
sim2 = nengo_loihi.Simulator(model, dt=0.0005)
```
![image](https://user-images.githubusercontent.com/2380772/47138810-6794f280-d288-11e8-9097-2059a3404621.png)

```python
sim2 = nengo_loihi.Simulator(model, dt=0.0001)
```
![image](https://user-images.githubusercontent.com/2380772/47138835-75e30e80-d288-11e8-8df8-5e85c4c8b194.png)

Alternatively, we can make the problem completely go away by switching to a weight solver (and thus not having interneurons):

```python
    solver = nengo.solvers.LstsqL2(weights=True)
    nengo.Connection(a, c, solver=solver)
    nengo.Connection(b, c, solver=solver)
```
![image](https://user-images.githubusercontent.com/2380772/47138906-9b701800-d288-11e8-9743-735b641d3236.png)

I believe this may have something to do with the integrator stability problems (#114 and the nengo_benchmarks), as the integrator is supposed to work by adding its input to the recurrent value.

Interestingly, some input values work better than others:

```python
    stim_a = nengo.Node(1)
    stim_b = nengo.Node(-1)
```

![image](https://user-images.githubusercontent.com/2380772/47139334-8d6ec700-d289-11e8-8625-b1a9f7d605e1.png)

```python
    stim_a = nengo.Node(0.5)
    stim_b = nengo.Node(-1)
```
![image](https://user-images.githubusercontent.com/2380772/47139362-9e1f3d00-d289-11e8-8f39-9c01dca94451.png)

```python
    stim_a = nengo.Node(1)
    stim_b = nengo.Node(0)
```

![image](https://user-images.githubusercontent.com/2380772/47139374-b1320d00-d289-11e8-81bd-f50897a86779.png)

**Comment by drasmuss** [comment]
This was improved significantly in #132.  There are still other opportunities for improvement I'm sure, but I'll close this for now and we can open new issues for more specific improvements as they come up.
