### ISSUE TITLE
Revisit PES error magnitude expectations

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo-loihi#14]
At https://github.com/nengo/nengo-loihi/blob/master/nengo_loihi/simulator.py#L498 it seems as though we are getting the error from the host, doing `x = int(100 * x)`, and then sending it to the chip. There's a comment in that block of code saying >128 is an issue on chip; @drasmuss noted:

> The comment says 128 but the code uses 100? Also is this assuming that errors will be <= 1, or is that handled elsewhere somehow?

If we are making an assumption about error magnitudes, we should be explicit about it. In my experience, error values are very rarely going to be this high, so we might get better performance by looking at a tighter range of error values (say from -0.2 to 0.2).

**Comment by drasmuss** [comment]
#139 added a configurable `pes_error_scale` parameter which can be used to adjust this.  Do you think that's enough to consider this resolved?

**Comment by drasmuss** [comment]
Yeah, assuming that errors are +/-1, with the .28 fudge factor added, seems like an unsurprising default at least, even if it may not be optimal.
