### ISSUE TITLE
nengo_loihi=0.4.0 incompatible with nengo=2.8.1.dev0

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo-loihi#146]
Note this is being addressed by #142.

Currently on the master branch of `nengo` (after https://github.com/nengo/nengo/pull/1481 where `get_samples` was renamed to `get_transform`) and the master branch of `nengo_loihi` (release `0.4.0`).

Importing `nengo_loihi` raises:

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/arvoelke/CTN/nengo-loihi/nengo_loihi/__init__.py", line 7, in <module>
    from . import builder
  File "/home/arvoelke/CTN/nengo-loihi/nengo_loihi/builder.py", line 18, in <module>
    from nengo_loihi import conv
  File "/home/arvoelke/CTN/nengo-loihi/nengo_loihi/conv.py", line 8, in <module>
    from nengo.builder.connection import BuiltConnection, get_samples, slice_signal
ImportError: cannot import name 'get_samples'
```

But would it be better to do a minor patch that changes `setup.py` to require `nengo<2.8.1` (or exactly `2.8.0`) so that this dependency is somewhat enforced during install (especially thinking ahead to when `nengo=2.8.1` is released)? Moreover this dependency could be documented here: https://www.nengo.ai/nengo-loihi/overview.html#software

**Comment by arvoelke** [comment]
I think the warning isn't being triggered because the error is raised while it's still going through the imports?

I definitely see what you're saying in general and that makes sense to not enforce a blanket policy that would prevent combinations that could otherwise have worked in the future. But I thought this case is special as I do not (or, did not) expect that `nengo` would revert to supporting both `get_transform` and `get_samples`. Is that a possibility?

**Comment by drasmuss** [comment]
Ah you're right, I've been doing too much swapping back and forth between nengo-dl and nengo-loihi and got mixed up!  We should definitely add that same warning to nengo-loihi.

**Comment by drasmuss** [comment]
> But I thought this case is special as I do not (or, did not) expect that nengo would revert to supporting both get_transform and get_samples. Is that a possibility?

I suspect that the next release will be 3.0, so we probably won't be worrying about backwards compatibility.  In any case though, I would say that we still shouldn't try to "future proof" our setup.py requirements.

For a little more detail, the issue you're highlighting is essentially the difference between `install_requires` and `requirements.txt`.  `install_requires` specifies the minimum requirements to get things working (intentionally leaving things open-ended to allow flexibility in the future).  `requirements.txt` specifies a specific build environment that is guaranteed to work.  You can read more about this at https://packaging.python.org/discussions/install-requires-vs-requirements/.  We don't provide a `requirements.txt` for nengo-loihi, but we could if this seems to be an issue that users are commonly running in to.

**Comment by arvoelke** [comment]
To keep this issue focused constructively on the specifics at hand, my concern is the following scenario:
 - `nengo=2.8.1` is released as is.
 - A user comes along and obtains the most recent releases (`nengo_loihi=0.4.0` and `nengo=2.8.1`).
 - The user's environment is now broken.

Without getting into a discussion about what to do about this more generally, it sounds to me like there are the following options in this case:
 1. We are okay with the above situation (no resolution needed).
 2. This is a `nengo` core issue that should be resolved by adding back `get_samples` before releasing `2.8.1`.
 3. This is a `nengo-loihi` issue that should be resolved by releasing a minor patch that requires `nengo=2.8.0`, either now or in sync with the `2.8.1` release, since that becomes a minimal requirement for the software to function.

Sorry if this is coming across as overly-direct, but again I'm trying to focus on the specifics, and this issue was created to propose solution number 3 to this real scenario. Admittedly I had not thought of solution 2 at the time, but think that is also completely viable. But feel free to close this if solution 1 is the call for this case.

**Comment by drasmuss** [comment]
> Which sounds like you are also suggesting 3 then in this case?

Yes I think we're in agreement :) I was just saying that we shouldn't worry about compatibility between nengo-loihi and nengo master.

**Comment by drasmuss** [comment]
The latest nengo-loihi release (0.6.0) is now compatible with both nengo 2.8.0 and the development version.  Our plan is to maintain compatibility with both the latest release and development version in the future (although as always with development versions there may be temporary incompatibilities).

Note that we still haven't prohibited future versions (e.g., it is possible that a future nengo release will break nengo-loihi 0.6.0).  But that is a standard approach to dependency requirements in Python, as discussed above.

However, the fact that nengo-loihi will be up to date with nengo master means that the latest nengo-loihi release will never be too far behind nengo core (i.e., in the above scenario even if 0.6.0 is broken, there would be a 0.7.0 release soon available, or already available, that would not be broken).  Does that address your concerns?

**Comment by arvoelke** [comment]
Yep sounds good to me; should resolve the situation I was considering above. Closing, thanks!
