### ISSUE TITLE
Revisit xfailed tests

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo-loihi#166]
After #124 I am getting a lot more xpasses running the test suite on hardware, and likely other PRs in the queue will result in more Nengo Loihi and/or Nengo core tests passing, so we should determine if these tests now pass reliably and remove the xfail if they are.

**Comment by hunse** [comment]
`test_input_node`, which is responsible for a number (10) of our xfail/xpass tests, seems to fail stochastically, so it may be hard to determine conclusively if it always passes. I had hypothesized that it may fail because of interneuron issues, so I'd suggest revisiting it once #132 is merged.

**Comment by drasmuss** [comment]
This has been done in a combination of merged PRs
