### ISSUE TITLE
Testing issues

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo-loihi#17]
Currently we have some tests failing and some xpassing. We should go through and fix all failing tests. Also, because of #5 we should do this by running each test file individually for now.

**Comment by tbekolay** [comment]
When investigating this, one way around the issue filed in #5 is to loop over all the test files and run them separately. Here's one way to do that:

```bash
shopt -s globstar
for test in **/test*.py; do pytest --target loihi -sv $test; done
```

The `globstar` option enables the `**` in the second command.

**Comment by drasmuss** [comment]
I believe all these are fixed or tracked in more specific issues now
