### ISSUE TITLE
Make Loihi learning deterministic

### ISSUE THREAD

**Issue by hunse** [nengo/nengo-loihi#184]
#140 adds a test that learning is deterministic on the emulator. Currently this test fails on the chip, but it should be possible to get it working. Andreas says that the seeds on the chip should start out the same each time the chip is initialized, so that part should be reproducible. (There are also values that we can set ourselves to change the seed or make sure things are deterministic there.) There could be ordinary dictionaries used in the hardware builder that make it non-deterministic, so we should check for that.

**Comment by arvoelke** [comment]
Is this still an issue? It looks like `test_pes_deterministic` is running on the hardware and passing.

**Comment by hunse** [comment]
Fixed in #140, a92dbb96a46942fe35a93c2860c20ad1a6fa0811.
