### ISSUE TITLE
Better rules for splitter

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo-loihi#20]
In our PES learning example, I had to mark two ensembles as being simulated off-chip because the splitter wanted to put them on the chip. It's useful, I think, to always have the ability to mark ensembles as on- or off-chip, but it shouldn't be necessary for a simple PES learning example. I think modifying the splitter to work on connections first (instead of last) will make it possible to detect the learning rule case. Or, we might have to do multiple passes over the network.

**Comment by drasmuss** [comment]
Resolved in #112
