### ISSUE TITLE
Keyword spotting performance

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo-loihi#21]
Originally reported by @pblouw:

> I've been playing around with running the speech demo over all of the test examples (n=192) by creating a bash script that repeatedly runs the demo script on different subsets of the 192 examples while writing the number of true positives and false negatives in each case to a file. When I do this, I'm getting an overall accuracy rate of 67.7%, which is ~20% drop in absolute performance from CPU Nengo (and the demo in Feb). Looking through the output, it seems like a lot of the errors involve an extra letter being tacked on at the beginning of the transcription (e.g. "taloha", "ealoha").
>
> Anyway, thought I'd flag this in case it's unexpected (or someone else has gotten better results than me, in which case I'll double check my script). Also happy to help out if this is something that requires some work to sort out.

@hunse:

> I noticed the same thing when I was running the demo about a month ago (wrt the extra letters). I'm not sure if I know enough about the speech demo to know why it might tack letters on the beginning. How does it decide when it's heard a letter? Might have to sit down and talk about this with people who know the demo better.
>
> Thanks for doing a proper benchmarking of this test, @pblouw. When I did it originally I just tested to make sure it was roughly working, so I didn't realize the discrepancy is so large.

@pblouw:

> For predicting letters, the model maps from input features (MFCCs for some window in the original audio signal) to distributions over characters. Right now each MFCC feature vector is presented for 10ms, and on the output side, the most frequent character prediction over those 10ms is appended to the transcription. (The 10ms corresponds to the window stride in the original audio signal). So you basically get a long string of characters once a whole utterance is passed through the model (e.g. "aaaalllooooohaaaa"). Then, you collapse any repeated characters and strip out a special character '-' that is used to predict repeated characters. (This is all standard stuff for doing speech recognition with neural nets).
> 
> My best guess for what is going on is that the model is having a hard time consistently predicting either the empty character (i.e. ' ') or the special blank character (i.e., '-') during relatively silent parts of the input. In other words, you want the empty character to always be the default prediction, and if this default is not quite strong enough, you could have for example 10 input windows for which each prediction should ' ', but one of the ten produces some other letter - this would be enough to tack a random character on the front. (e.g. something like '    t     aaaaalloooohhaaaaa     ' would get collapsed down to 'taloha', yielding a false negative prediction).

@hunse:

> That explanation makes sense to me.
>
> In that case, I wouldn't be surprised if the difference could be because of how the weights or biases are discretized. Some rounding in these could cause the occasional error where a blank is misinterpreted as a character. Particularly, for example, if the model relies on many small negative weights to inhibit downstream neurons and stop them from firing.
>
> If our method for converting floating-point to fixed-point weights was better in the original demo, then it could have avoided more of these rounding problems.
>
> There is a floating point version of the simulator (pass `target='simreal'` to the `Simulator`). I think this version of the simulator should get the same results as core Nengo. We could check this, to make sure the problem is with the rounding as I expect.

@pblouw:

> Cool, sounds like a promising fix to check. Otherwise, the only thing I can think of is that there's a difference between regular nengo and loihi involving the spike amplitude stuff (not sure how that gets handled on the chip, but it looks like you are scaling all the weights by a constant in notebook).
>
> I just ran the floating point version, and this bumps the accuracy up to 79.2%, which is definitely an improvement, but still not quite at the level of the regular Nengo implementation of the model (87.5% accuracy).

**Comment by drasmuss** [comment]
I believe the keyword spotting importance has improved in more recent work, is this resolved or is there still a gap between nengo and nengo-loihi that we think could be closed? (@pblouw @hunse)

**Comment by hunse** [comment]
This is fully resolved. In the newest results, there's no difference between Loihi and the ANN model. See version 2 of the paper here: https://arxiv.org/abs/1812.01739
