### ISSUE TITLE
Allow pop16 connections to work with all offsets

### ISSUE THREAD

**Issue by hunse** [nengo/nengo-loihi#262]
Pop16 axons by design do not support compartment offsets ("bases") that are not multiples of 4. Rather than restricting the types of connections on which we can use pop16 axons (in the case of convolutional connections, those with `channels_last=True` and a number of filters that is a multiple of 4), we could make copies of the weights in the case that we need offsets that are not multiples of 4, such that we have up to 4 copies each for a different modulo of the offset.

**Comment by drasmuss** [comment]
This is done
