### ISSUE TITLE
Do we support Nengo 2.8.0?

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo-loihi#263]
We should decide and then make some updates depending on the decision. Some things we might do:

- Remove Nengo 2.8.0 compat stuff in `compat.py`
- Modify the min Nengo version in `version.py`
- Add a TravisCI job to test on 2.8.0

**Comment by drasmuss** [comment]
Decision was that we would not support 2.8.0, so we just need to go and remove the 2.8.0 backwards compatibility code.

**Comment by drasmuss** [comment]
This has been done (in fact we now exclusively support 3.1.0).
