### ISSUE TITLE
Error in installation instructions

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo-loihi#265]
The installation instructions say:

> Activate your new environment.
> 
> ```
> source activate loihi
> ```

I believe that should be `conda activate loihi`

**Comment by xchoo** [comment]
Both `source activate` and `conda activate` are valid, depending on how conda is set up on the various systems. On `intelhost`, it's `source activate`, on `abrhost` (i think it's because it's a new conda install) it's `conda activate`.

**Comment by tcstewar** [comment]
Ah, okay.  I was just rather confused because all of the other instructions on that page using `conda ...` style instructions....

**Comment by xchoo** [comment]
Once the conda environment is activated (either through `source` or `conda`), all of the `conda` commands are initiated with `conda`.

**Comment by xchoo** [comment]
I'm closing this issue for now, feel free to open it if you have further questions. :)
