### ISSUE TITLE
Allow population axons on dense connections

### ISSUE THREAD

**Issue by hunse** [nengo/nengo-loihi#280]
Dense connections do not use the compartment offset (i.e. it's always 0 for all axons), so there's no reason we couldn't use population axons here to reduce the number of output/input axons. This is akin to expressing a dense connection as a convolutional connection with a 1x1 image shape (and maybe that's a viable workaround for doing this in the current setup).

**Comment by drasmuss** [comment]
Result of internal discussion is that we'll just recommend manually doing the 1x1 convolutional connection for now, unless more demand crops up for this.
