### ISSUE TITLE
Moving things on/off chip changes seeds

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo-loihi#29]
As seen in #24, whether an object is simulated on or off chip changes its seed when the network is seeded because the splitter moves the object, changing the seeds on both the chip and host. To get around it, you can set the seed on the object itself, but I think the seed changes would be surprising to most users.

**Comment by hunse** [comment]
Addressed in #70.

**Comment by drasmuss** [comment]
#70 is merged in now
