### ISSUE TITLE
maximum of 1024 compartments

### ISSUE THREAD

**Issue by biphasic** [nengo/nengo-loihi#291]
Hello, 
I'm trying to run the Nengo [Lorenz attractor example](https://www.nengo.ai/nengo/examples/dynamics/lorenz-attractor.html) on Loihi. 

I'm using nxsdk 0.9, Nengo 3.0.0 and Nengo-loihi 0.10.0.

when I replace the last lines with 
```python
with nengo_loihi.Simulator(model) as sim:
    sim.run(10)
```
it returns `BuildError: Number of compartments (2000) exceeded max (1024)`. 

I then tried to set the environment variable to run on a different partition with more chips, which didn't change anything.
`%env PARTITION nahuku32`

Then I tried passing the number of chips to the hardware config like the following:
```python
with nengo_loihi.Simulator(model, target='loihi', hardware_options={
    "n_chips": 2,
}) as sim:
    sim.run(10)
```
which returns `TypeError: __init__() got an unexpected keyword argument 'n_chips'`

Can you please advise what I'm doing wrong. Thank you

**Comment by tbekolay** [comment]
Hi @biphasic, the 1024 compartment limitation is lifted in the master branch of this repository, but it hasn't been released, hence why you're still getting the error. If you clone this repository and install it from there (`git clone https://github.com/nengo/nengo-loihi.git` then `pip install -e nengo-loihi`) the example should run without modifications. You won't need to pass in hardware options, though you will be able to in the master branch.

**Comment by biphasic** [comment]
wow thank you for the quick answer! Greatly appreciated.
