### ISSUE TITLE
Check that Python >= 3.5

### ISSUE THREAD

**Issue by hunse** [nengo/nengo-loihi#31]
In nengo_loihi's `__init__` file, I think we should check that the python version is new enough. Not only do we need this for working with NxSDK, but we also have a star expression in `simulator.py` (`items.append((sent_count, *output_axon[j]))`) that uses new Python syntax. Right now, if you try to import with older Python, you get a somewhat-cryptic syntax error.

**Comment by tbekolay** [comment]
Right now NxSDK needs < 3.6 too, so if we're going to limit it based on NxSDK we should check for both. The emulator doesn't have those restrictions though, so should we fix the Python 2 compat stuff instead? There probably isn't much to it and if people are just trying things out might be worth having it work in Python 2. But I'm fine either way, also convenient to not have to deal with Py2/3 in a single codebase.

**Comment by hunse** [comment]
So the emulator now works with all of Python 3.

Do we want any checks for `nxsdk`? Really, this is something that `nxsdk` should be checking in it's `setup.py` file, but as far as I know it still doesn't have a `setup.py` file. I'm tempted to say "no" to this, and close this issue for now.

**Comment by tbekolay** [comment]
Yeah I would leave that up to `nxsdk` and consider this issue closed.
