### ISSUE TITLE
Nengo-Loihi compatibility issue with NxSDK 1.0.0

### ISSUE THREAD

**Issue by sanchitchip** [nengo/nengo-loihi#316]
Hi,
I have been trying to use Nengo-Loihi(1.0.0) with the recent release of NxSDK 1.0 on my Ubuntu 20 and I think there are compatibility issues between the different versions. 
I mainly wanted to know if there is going to be an update or new release soon to run Neng-Loihi with NxSDK 1.0.0.
I am also attaching a screenshot of the error I get when I try to import Nengo_loihi.
![import problem](https://user-images.githubusercontent.com/7767884/116695308-ba56d580-a9c0-11eb-9168-6bb114593b48.png)

Thank you very much.

**Comment by hunse** [comment]
NengoLoihi has not yet been updated to support NxSDK 1.0.0. We plan to do an update when the INRC server has been upgraded to Ubuntu 20.04, which should be in the next month or so. For now, you'll have to use an older version of NxSDK which is supported by NengoLoihi, or you can try to patch NengoLoihi yourself (I think the only thing that needs to be patched is the import location for `N2Board`, which according to the NxSDK 1.0.0 release notes should now be imported from `nxsdk.arch.n2a.n2board`).

**Comment by hunse** [comment]
Awesome, glad it works! I'll keep this issue open until we have an NxSDK 1.0.0 patch merged.

**Comment by hunse** [comment]
Patch is here: #317.

**Comment by hrostrog** [comment]
Hello, 

How is done this patch? could you please specify where or how to apply this patch? Thank you in advance

**Comment by hunse** [comment]
@hrostrog The easiest way is probably to ask pip to install the `nxsdk100` branch with the patch: `pip install git+https://github.com/nengo/nengo-loihi.git@nxsdk100`. Alternatively, you can download the source from this repo, checkout that branch, and install from source.

**Comment by hunse** [comment]
This patch is now in `master` branch, and will be included in the next release (slated for January 2022). If you'd like to take advantage of it now, you can install from source by cloning this repo or with `pip install git+https://github.com/nengo/nengo-loihi.git`.
