### ISSUE TITLE
Global state from running many models in a row

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo-loihi#5]
Currently `nxsdk` seems to keep around some global state, making it impossible to run many models in the same Python process. This can be worked around by closing the process and starting another one (e.g., by batching models into small groups and iterating over the batches in the shell), or possibly by using the `multiprocess` modules in Python.

However, it would be good to track down the global state and clear it, if we can. One thing that seems to be tracked globally is spike counters, as running many models eventually results in the following:

```
Exception: All the Spike Counters are being Used : Cannot Create a new one
```

However, there are likely other issues, as running many models in succession often results in random hangs that are fixed by running the model again by itself.

**Comment by drasmuss** [comment]
I believe this is resolved.  Spike counters were fixed in #68, and the only remaining test hangs are tracked in #84
