### ISSUE TITLE
Add assert to `test_loihi_cx.py:test_simulator_noise`

### ISSUE THREAD

**Issue by hunse** [nengo/nengo-loihi#52]
Need to make sure this works as expected on Loihi.

**Comment by drasmuss** [comment]
This is done I believe?

**Comment by tbekolay** [comment]
There is [an assert](https://github.com/nengo/nengo-loihi/blob/40981e48895df92f0a2904f2f89477990d077f2b/nengo_loihi/tests/test_simulator.py#L549), though the tolerances are suspiciously large... but it is noise :man_shrugging:

**Comment by drasmuss** [comment]
Going to close this one then.  There are probably several tolerances that we could revisit throughout the test suite, but we'll tackle that in its own issue I figure.
