### ISSUE TITLE
Add forumula for refractory period numbers

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo-loihi#6]
The chip uses magic voltage numbers to indicate their point in the refractory period; we hard code a few of these (e.g. https://github.com/nengo/nengo-loihi/blob/master/nengo_loihi/simulator.py#L608). But we should use the formula for determining these numbers instead, which should be in documentation somewhere (based on `RefractDelay`).

**Comment by hunse** [comment]
Done in #78
