### ISSUE TITLE
Set default solver to use weights

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo-loihi#72]
Wanted to note this in case I forget! We should make this quick one-line change to `nengo_loihi.config.set_defaults`; it might not affect everything, but it will probably improve accuracy on our test suite.

**Comment by hunse** [comment]
I would like to try this on some bigger models before we make the change. It works well for smaller ensembles, but my guess is if we wanted to connect e.g. a 400 neuron population to another 400 neuron population, we'd run out of synapse memory (if I'm calculating correctly, we have `2**14 * 64` bits of memory, and if we're using 8 bits per weight that's about 130000 weights).

Maybe we could have an option that we pass to `set_defaults` that can easily turn this on or off. We could also have a "smart" system that looks at connection sizes and only does this for smaller connections, but that starts to get kinda complicated.

**Comment by tcstewar** [comment]
Hmm, I'm also not quite sure we could do it with a one-line change to `set_defaults`....  setting `nengo.solvers.LstsqL2.weights.default = True` doesn't work:

```python
import nengo
model = nengo.Network()
nengo.solvers.LstsqL2.weights.default = True
with model:
    stim = nengo.Node([0])
    a = nengo.Ensemble(n_neurons=50, dimensions=1)
    b = nengo.Ensemble(n_neurons=50, dimensions=1)
    c1 = nengo.Connection(stim, a)
    c2 = nengo.Connection(a, b)
print(c1.solver)
print(c2.solver)
```
gives you this:
```
LstsqL2(reg=0.1, solver=Cholesky(transpose=None), weights=False)
LstsqL2(reg=0.1, solver=Cholesky(transpose=None), weights=False)
```

Also, doing it with the config system directly reveals this problem:
```python
import nengo
model = nengo.Network()
model.config[nengo.Connection].solver = nengo.solvers.LstsqL2(weights=True)
with model:
    stim = nengo.Node([0])
    a = nengo.Ensemble(n_neurons=50, dimensions=1)
    c1 = nengo.Connection(stim, a)
```
```
Traceback (most recent call last):
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\page.py", line 224, in execute
    exec(compiled, code_locals)
  File "<nengo_gui_compiled>", line 7, in <module>
  File "c:\users\terry\documents\github\nengo\nengo\base.py", line 35, in __call__
    inst.__init__(*args, **kwargs)
  File "c:\users\terry\documents\github\nengo\nengo\connection.py", line 437, in __init__
    self.solver = solver  # Must be set before learning rule
  File "c:\users\terry\documents\github\nengo\nengo\base.py", line 108, in __setattr__
    super(NengoObject, self).__setattr__(name, val)
  File "c:\users\terry\documents\github\nengo\nengo\config.py", line 456, in __setattr__
    reraise(exc_info[0], exc_info[1], None)
  File "c:\users\terry\documents\github\nengo\nengo\utils\compat.py", line 110, in reraise
    raise value.with_traceback(tb)
nengo.exceptions.ValidationError: Connection.solver: weight solvers only work for connections from ensembles (got 'Node')
```

**Comment by tcstewar** [comment]
As an even bigger problem, now that I think about it, we can't do this *before* passthrough Nodes are eliminated.  Because Nengo won't allow a `weights=True` solver on a connection that goes to or from a passthrough Node....   So that makes me think that this needs to be done with some sort of helper function approach, even if we don't go with the full "smart" system @hunse describes....

**Comment by tbekolay** [comment]
Interesting... I was envisioning the latter method you posted @tcstewar. I think the exception there is a bug in Nengo as we shouldn't care about the solver in a connection from a node (since we don't use it). We don't use weight solvers that often so we likely haven't run into the issue yet, but yeah that's a Nengo bug IMO.

**Comment by tcstewar** [comment]
Ah, good point about that being a bug....  but going the other way around is still a problem:
```python
    n = nengo.Node(None, size_in=1)
    a = nengo.Ensemble(n_neurons=50, dimensions=1)
    nengo.Connection(a, n)
```
```
Traceback (most recent call last):
  File "c:\users\terry\documents\github\nengo_gui\nengo_gui\page.py", line 224, in execute
    exec(compiled, code_locals)
  File "<nengo_gui_compiled>", line 7, in <module>
  File "c:\users\terry\documents\github\nengo\nengo\base.py", line 35, in __call__
    inst.__init__(*args, **kwargs)
  File "c:\users\terry\documents\github\nengo\nengo\connection.py", line 437, in __init__
    self.solver = solver  # Must be set before learning rule
  File "c:\users\terry\documents\github\nengo\nengo\base.py", line 108, in __setattr__
    super(NengoObject, self).__setattr__(name, val)
  File "c:\users\terry\documents\github\nengo\nengo\config.py", line 456, in __setattr__
    reraise(exc_info[0], exc_info[1], None)
  File "c:\users\terry\documents\github\nengo\nengo\utils\compat.py", line 110, in reraise
    raise value.with_traceback(tb)
nengo.exceptions.ValidationError: Connection.solver: weight solvers only work for connections to ensembles (got 'Node')
```

**Comment by tbekolay** [comment]
Right right that is definitely a case that won't work ... it feels as though Nengo should handle this more gracefully, but that'd be a big change so I'll consider this issue closed and start a new one for the automatic model tuning.

**Comment by tcstewar** [comment]
I've added an initial attempt at implementing this here: #74
