### ISSUE TITLE
Spike probes with precompute=True hang for neurons other than LIF(tau_ref=0.002)

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo-loihi#77]
This is the cause of the hanging tests identified in 6ecae38ac28eac8fcf810bdcd73ff911cdd0eaf1 and it is due to this old issue #6 

I'm not sure why it just hangs rather than giving the exception and/or assertion failure that should be happening.

To be more specific, this is the problematic code:
```python
                       if isinstance(probe.target, nengo.ensemble.Neurons):
                            t_ref = probe.target.ensemble.neuron_type.tau_ref
                            assert t_ref == 0.002
                            # TODO: generalize this to other tau_ref values
                            x = (x == 384)
```

That will give an assertion failure for LIF with tau_ref != 0.002, and it'll give an Exception for neuron types that don't have tau_ref (i.e. SpikingRectifiedLinear)

**Comment by hunse** [comment]
Addressed by #78.
