### ISSUE TITLE
Only add encoders if they're used

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo-loihi#8]
As suggested by @hunse: in 8a1420ff9769eb98d3a we can now have ensembles with only connections into their neurons. This means that the encoders are not used. However, the unused encoders will still affect how the weight and vth scaling is chosen in `discretize`. It is probably best to remove them if they're not used (or rather don't add them until a connection in the builder specifically asks for them), both for better weight scaling, and so they don't take up space on the chip.

**Comment by hunse** [comment]
Fixed in #44.
