### ISSUE TITLE
Refactor builder logic

### ISSUE THREAD

**Issue by drasmuss** [nengo/nengo-loihi#80]
Right now our build logic is split across two qualitatively different phases, the splitter and the builder.  This allowed us to get a prototype running quickly, but it's definitely a big awkward to work with.  For example, if you want to understand how the radius is handled for an Ensemble, maybe you need to look at `build_ensemble`, maybe you need to look at `split` (on a Connection object), depending not only on whether that ensemble is on/off chip, but whether the presynaptic objects connected to that Ensemble are on or off chip. 

I think we could simplify the build logic a lot by integrating all the builder logic into the regular build process.  Basically this means handling the splitting through the backend, rather than by rearranging the front-end network objects.  This would be a significant change and a longer-term TODO item, but worth doing I think (perhaps after the next release).

**Comment by tcstewar** [comment]
I definitely agree this would be good to look into.  That said, I've never managed to make a backend work well that way -- I've never been able to come up with the right set of abstractions that work for both the splitting/organizing-IO part and the builder/mapping-to-hardware part.  There are definitely a few annoyances with using the nengo abstractions for the splitter part, but for the most part I've been pleasantly surprised with how well they have worked for a task that they really weren't designed for.

Oh, and while I'm thinking about it, the third aspect that's probably also going to interact tightly with the two mentioned here is the splitting-an-ensemble-across-cores aspect (which we don't have in nengo-loihi yet).  I would love to see someone take a stab at making a good design for all that, and figuring out what good abstractions are, but I don't know what that would look like at all.  :)
