### ISSUE TITLE
Nengo_loihi doesn't like n_neurons=300

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo-loihi#84]
For some reason, `nengo_loihi` consistently hangs if you have an ensemble with exactly 300 neurons.  This does not happen for `n_neurons=299` or for `n_neurons=301`.

```python
import nengo
import nengo_loihi

with nengo.Network() as net:
    stim = nengo.Node(0)
    a = nengo.Ensemble(300, 1)
    nengo.Connection(stim, a, synapse=None)

with nengo_loihi.Simulator(net, precompute=True) as sim:
    sim.run(1.0)
```

With `precompute=True` we get to this point and then hang:
```
Connecting to loihimh:18861
N2Driver: Running...
    Compiling synapses... Done (0.00s)
    Processing probes... Done (0.00s)
    Writing modified registers... Done (0.07s)
    Initializing... Done (0.01s)
    Preparing input... Done (0.03s)
```

With `precompute=False`, we get this:
```
Lakemont_driver...
Initializing Network
Starting the Execution
```

This is the cause of the two hanging tests here: https://github.com/nengo/nengo-loihi/commit/e7a18f35f1038ac77a676baa0376a46a88db0b04

**Comment by drasmuss** [comment]
This was resolved by a new `nxsdk` release.
