### ISSUE TITLE
Teach users about initial PES functions

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo-loihi#99]
As we found out in #89, the choice of the initial function across a PES learned connection can affect its behavior significantly. While we should determine more robust ways to discretize in the long term (see #83), in the short term we should at least attempt to inform users that this choice makes a big difference.

A few ideas on how we might do this:

- Make an example showing how different things can be given the initial function (similar to what's in the #89 comment thread)
- Raise a warning either at model construction or model build time if the user has made a learned connection and specified a function. This is similar to what we're doing with connection from nodes with `synapse=None` right now. This assumes that the identity function (communication channel) always puts weights in a decent range, which might not be true.

**Comment by drasmuss** [comment]
I believe the discretization has been improved so that using an all-zero initialization no longer causes things to fall apart, @hunse can confirm?

**Comment by hunse** [comment]
Yep. We now test initializing with zeros, too: https://github.com/nengo/nengo-loihi/blob/master/nengo_loihi/tests/test_learning.py#L37
